"""add is_active to time_off

Revision ID: b99f0c44998d
Revises: 65c52accc292
Create Date: 2026-02-02 16:51:41.224823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99f0c44998d'
down_revision: Union[str, Sequence[str], None] = '65c52accc292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_off', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('time_off', sa.Column('end_at', sa.DateTime(), nullable=False))
    op.add_column('time_off', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_time_off_is_active'), 'time_off', ['is_active'], unique=False)
    op.drop_column('time_off', 'start_dt')
    op.drop_column('time_off', 'end_dt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_off', sa.Column('end_dt', sa.DATETIME(), nullable=False))
    op.add_column('time_off', sa.Column('start_dt', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_time_off_is_active'), table_name='time_off')
    op.drop_column('time_off', 'is_active')
    op.drop_column('time_off', 'end_at')
    op.drop_column('time_off', 'start_at')
    # ### end Alembic commands ###
