"""add staff service entity

Revision ID: e05a1b8c85bd
Revises: 2a3e3dcee3aa
Create Date: 2026-01-31 17:08:19.066955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05a1b8c85bd'
down_revision: Union[str, Sequence[str], None] = '2a3e3dcee3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_services', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('staff_services', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('staff_services', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('staff_services', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_staff_services_id'), 'staff_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_services_id'), table_name='staff_services')
    op.drop_column('staff_services', 'is_active')
    op.drop_column('staff_services', 'duration')
    op.drop_column('staff_services', 'price')
    op.drop_column('staff_services', 'id')
    # ### end Alembic commands ###
