"""add is_active to booking

Revision ID: ed0a0dd18762
Revises: b99f0c44998d
Create Date: 2026-02-02 16:55:10.418475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0a0dd18762'
down_revision: Union[str, Sequence[str], None] = 'b99f0c44998d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('end_at', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_bookings_end_dt'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_dt'), table_name='bookings')
    op.create_index(op.f('ix_bookings_end_at'), 'bookings', ['end_at'], unique=False)
    op.create_index(op.f('ix_bookings_is_active'), 'bookings', ['is_active'], unique=False)
    op.create_index(op.f('ix_bookings_start_at'), 'bookings', ['start_at'], unique=False)
    op.drop_column('bookings', 'start_dt')
    op.drop_column('bookings', 'end_dt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('end_dt', sa.DATETIME(), nullable=False))
    op.add_column('bookings', sa.Column('start_dt', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_bookings_start_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_is_active'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_at'), table_name='bookings')
    op.create_index(op.f('ix_bookings_start_dt'), 'bookings', ['start_dt'], unique=False)
    op.create_index(op.f('ix_bookings_end_dt'), 'bookings', ['end_dt'], unique=False)
    op.drop_column('bookings', 'is_active')
    op.drop_column('bookings', 'end_at')
    op.drop_column('bookings', 'start_at')
    # ### end Alembic commands ###
