"""use composite pk for staff_services

Revision ID: fe98ab6a7125
Revises: e05a1b8c85bd
Create Date: 2026-01-31 17:43:32.490845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe98ab6a7125'
down_revision: Union[str, Sequence[str], None] = 'e05a1b8c85bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_services_id'), table_name='staff_services')
    op.drop_column('staff_services', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_services', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_index(op.f('ix_staff_services_id'), 'staff_services', ['id'], unique=False)
    # ### end Alembic commands ###
